### ISSUE TITLE
login to mavinote account.

### ISSUE THREAD

**Issue by maxongshD** [bwqr/mavinote#14]
login to mavinote account not working. 
i'm writing my email and tap on "request verification", but email message from mavinote (for verification) don't receive. 
reinstalling not help.

**Comment by bwqr** [comment]
Hi @maxongshD.  Have you already created an account with the email you are trying? Because `Request Verification` step must be used when you already have an Mavinote account and you want to add a new device. Another question is that are you selecting `Add an Existing Account` option or `Create a New Account` option in the `Add Account` page

**Comment by maxongshD** [comment]
i have a mavinote account.
i click "request verification", a window pops up notifying me that an email
has been sent to my email. but the letter does not come, which means that i
can not log into my account.

**Comment by bwqr** [comment]
I assume that you are selecting `Add an Existing Account` option under the `Add Account` page, and this device is a different device than the one you have created Mavinote account. If they are the same device, that means you have uninstalled the Mavinote application after you have created the account. In this case, there are some steps that you have to manually apply (just reply in the message if you have done like this, then I can explain the manual steps).

If you are seeing a message similar to one in the image below, this actually does not mean an email is sent to your email address (I accept that the message could be much clearer). It actually tells you that the server waits a verification from a device that you have created the account with the given email. Email you have typed in this case is used for identifying which account you want to add, not for sending a verification code again. You need to add this new device from the other device you have created account.

![20230824_18h00m58s_grim](https://github.com/bwqr/mavinote/assets/16965054/91aa4491-2bc9-4edf-a237-a9a5eec16247)

**Comment by maxongshD** [comment]
@bwqr the device from which i registered the mavinote account and from which i want to log into the account are the same.
after creating an account, saving a few notes (test notes), i deleted the application, and now i can’t log into my account.

**Comment by bwqr** [comment]
Unfortunately, you have to close your account and reopen since the private key and device password stored on your device are lost. Right now, Mavinote application do not provide a user interface for closing an account which is not yet added to the device. You have only one option to close your account manually: I have to identify your email and delete it from the server database without disclosing it publicly for your privacy. I can even identify your account If you can remember when you first created your account (was it 8th August?).

**Comment by maxongshD** [comment]
@bwqr yes, it was august 8th.
if possible, please delete my account. there was no important data there, except for a test note (mavinote it's simple and cool notes app).

**Comment by bwqr** [comment]
Thanks for the confirmation. Can you retry creating a new account please (Not adding an existing account)?

**Comment by maxongshD** [comment]
@bwqr 
![Screenshot_2023-08-25-20-54-19-66_8607cb0351b0be35f53fe52d8e616dff](https://github.com/bwqr/mavinote/assets/142055169/c4f51b4e-5beb-4144-9d62-1af3df9ef863)
yes, dear friend, working fine! thank you😊
please, tell me: what me need make for not get this problem?

**Comment by bwqr** [comment]
You are welcome. But you have shown your email to the public :sweat_smile: (this is what I was trying to avoid for your privacy). Anyway, if you want to avoid this, you need to close your account under account details before uninstalling the application. You can reach out to the account details by tapping your email name as shown in the image you have posted.

**Comment by maxongshD** [comment]
@bwqr thank you. i deleted that screenshot so as not to expose you and myself😅
will closing an account delete account information?

**Comment by bwqr** [comment]
You are welcome. But you have shown your email to the public :sweat_smile: (this is what I was trying to avoid for your privacy). Anyway, if you want to avoid this, you need to close your account under account details before uninstalling the application. You can reach out to the account details by tapping your email name as shown in the image you have posted.

**Comment by bwqr** [comment]
Yes, it will nuke all of your information related to your account from the server.
Edit: it will also delete all of the notes and folders related to the account from your device.

**Comment by maxongshD** [comment]
@bwqr best for me it's don't delete or reinstall this app. just using and happy😂
thank you, dear friend)

**Comment by maxongshD** [comment]
@bwqr what the fate of this app?

**Comment by bwqr** [comment]
Happy to hear that :smile: . The reason this app is born is that I wanted to experiment with a development idea, using a reactive shared library across multiple different applications. This is accomplished by developing two different applications,  android and ios, which use a common reactive shared library. 

I imagine that the next step would be developing web version of the application. Unfortunately there is a technical blocker: using sqlite and sqlx on wasm platform. Another step could be deploying the applications to the play store and app store. Then listen the feedbacks of users to improve the applications. However, right now, I have limited amount of time since I am employed for something else. Until I find lots of free time or some serious bugs arise in the applications, do not hope to see so much development around this project.

**Comment by maxongshD** [comment]
@bwqr thank you for replying)
i wish luck in all your plans and goals.
functional of this app will be expanded?
design (material you for android), and (or) functions export and import notes in archive (for local backup)?

**Comment by bwqr** [comment]
Actually, I was not planning to extend the functionality. But since you mentioned the backups, I might have to consider it. Taking backups is really important in my opinion.

**Comment by bwqr** [comment]
And @maxongshD thanks for your kind words.

**Comment by maxongshD** [comment]
@bwqr thank you dear for hearing my variants)
